### ISSUE TITLE
Unable to open multipage multichannel TIFF

### ISSUE THREAD

**Issue by jakirkham** [python-pillow/Pillow#2485]
Using this [image]( https://github.com/scikit-image/scikit-image/blob/883baa03282c8bf97fbd327e467850314b941fcd/skimage/data/multipage_rgb.tif ) (needs to be downloaded) from `scikit-image`, was unable to open the file with Pillow. The image file is a multipage RGB TIFF containing `float64` values. Code snippet and environment details below.

Code sample:

<details>

```python
In [1]: from PIL import Image

In [2]: im = Image.open("multipage_rgb.tif")
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-2-14749a0cbf47> in <module>()
----> 1 im = Image.open("multipage_rgb.tif")

/zopt/conda2/envs/pil/lib/python2.7/site-packages/PIL/Image.pyc in open(fp, mode)
   2347 
   2348     raise IOError("cannot identify image file %r"
-> 2349                   % (filename if filename else fp))
   2350 
   2351 #

IOError: cannot identify image file 'multipage_rgb.tif'
```

</details>

<br>
Conda environment:
<br>
<br>
<details>

```yaml
name: pil
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::appnope=0.1.0=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py27_0
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::freetype=2.7=1
- conda-forge::ipython=5.3.0=py27_0
- conda-forge::ipython_genutils=0.2.0=py27_0
- conda-forge::jpeg=9b=0
- conda-forge::libpng=1.6.28=0
- conda-forge::libtiff=4.0.6=7
- conda-forge::ncurses=5.9=10
- conda-forge::olefile=0.44=py27_0
- conda-forge::openssl=1.0.2k=0
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::pillow=4.0.0=py27_2
- conda-forge::prompt_toolkit=1.0.14=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::python=2.7.13=0
- conda-forge::readline=6.2=0
- conda-forge::scandir=1.5=py27_1
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::traitlets=4.3.2=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::xz=5.2.2=0
- conda-forge::zlib=1.2.11=0
prefix: /zopt/conda2/envs/pil
```

</details>
