### ISSUE TITLE
Test is failing with AttributeError for ppc64le

### ISSUE THREAD

**Issue by asellappen** [python-pillow/Pillow#5229]
### What did you do?

I am working for IBM to port cpu arch ppc64le for open sources , As a part of continuous integration on this package, We have applied changes , This helps us simplify testing later when distributions are re-building and re-releasing, We typically build applications for customers and ISVs, and while we don't use this package directly,
on the part this work , we are currently working on the package Pillow to support ppc64le.

### What did you expect to happen?
We included travis job for ppc64le and it fails in testing instead of 100% pass,The failure happens at test test_subifd  with AttributeErrorat ,but expectaion is should be passed.

### What actually happened?
Ps refer h=ob  https://travis-ci.com/github/asellappen/Pillow/jobs/477131803

```
Tests/test_file_tiff.py::TestFileTiff::test_subifd FAILED                [ 36%]
=================================== FAILURES ===================================
___________________________ TestFileTiff.test_subifd ___________________________
mode = '1', decoder_name = 'libtiff', args = ('1;I', 'group4', 13, 800)
extra = ()
    def _getdecoder(mode, decoder_name, args, extra=()):
    
        # tweak arguments
        if args is None:
            args = ()
        elif not isinstance(args, tuple):
            args = (args,)
    
        try:
            decoder = DECODERS[decoder_name]
        except KeyError:
            pass
        else:
            return decoder(mode, *args + extra)
    
        try:
            # get decoder
>           decoder = getattr(core, decoder_name + "_decoder")
E           AttributeError: module 'PIL._imaging' has no attribute 'libtiff_decoder'
/home/travis/virtualenv/python3.7.9/lib/python3.7/site-packages/Pillow-8.2.0.dev0-py3.7-linux-ppc64le.egg/PIL/Image.py:436: AttributeError
```

### What are your OS, Python and Pillow versions?

* OS: lunix - ubuntu bionic .
* Python: py 3.7 & 3.8
* Pillow: version      Pillow 8.2.0.dev0
* PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 8.2.0.dev0
platform     linux 3.8.7 (default, Jan  9 2021, 06:30:31)
             [GCC 5.4.0 20160609]

in travis.yml

added the below to support ppc64le
```yml
matrix:
    include:
        - python: 3.7
          env: TOXENV=py37
          sudo: true
        - python: 3.8
          env: TOXENV=py38
          sudo: true
        - python: pypy
          env: TOXENV=pypy
        - python: pypy3
          env: TOXENV=pypy3
        - python: 3.7
          env: TOXENV=py37
          sudo: true
          arch : ppc64le
        - python: 3.8
          env: TOXENV=py38
          sudo: true
          arch : ppc64le
before_install:
        - pip install hypothesis
```
