### ISSUE TITLE
Cannot use ImageField because Pillow is not installed

### ISSUE THREAD

**Issue by aleooo** [python-pillow/Pillow#5644]
In a Docker container I have installed package Pillow==8.3.1 (I also tried version 8.3.0). In Dockerfile I have dependencies:

```
RUN apk update \
   && apk add postgresql-dev gcc python3-dev musl-dev jpeg-dev zlib-dev libjpeg
```

when I execute the migrate command in the project Django.Shows me errors:
```
SystemCheckError: System check identified some issues:

ERRORS:
poszukiwania.Rzeczy.image_obverse: (fields.E210) Cannot use ImageField because Pillow is not installed.
        HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
poszukiwania.Rzeczy.image_reverse: (fields.E210) Cannot use ImageField because Pillow is not installed.
        HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow"
```
Python==3.8.10, Django==3.1.6
Any suggestions on how to fix this?
