### ISSUE TITLE
TooManyRedirects when installing Pillow with Poetry

### ISSUE THREAD

**Issue by Garrett-R** [python-pillow/Pillow#6360]
### What did you do?

I created an empty dir called `test_pillow`, then created a `pyproject.toml` file in it with this content:

```toml
[tool.poetry]
name = "hello"
version = "1.0.0"
description = "hello"
authors = ["Me"]

[tool.poetry.dependencies]
python = "3.10.4"
Pillow = "9.1.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

I then created a virtualenv for this dir.  Then I activated the virtualenv and did:
```shell
pip install poetry
poetry install
```

### What did you expect to happen?

It should just install Pillow.

### What actually happened?

This was the output:
```shell
(test_pillow) ~/Desktop/test_pillow $ poetry install
Updating dependencies
Resolving dependencies... (0.1s)

  TooManyRedirects

  Exceeded 30 redirects.

  at ~/.virtualenvs/test_pillow/lib/python3.10/site-packages/requests/sessions.py:191 in resolve_redirects
      187│             except (ChunkedEncodingError, ContentDecodingError, RuntimeError):
      188│                 resp.raw.read(decode_content=False)
      189│ 
      190│             if len(resp.history) >= self.max_redirects:
    → 191│                 raise TooManyRedirects(
      192│                     f"Exceeded {self.max_redirects} redirects.", response=resp
      193│                 )
      194│ 
      195│             # Release the connection back into the pool.

```

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.04
* Python: 3.10.4
* Pillow: 9.1.1
