### ISSUE TITLE
Add Codecov token to python-pillow org

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#8040]
Re: https://github.com/python-pillow/Pillow/pull/7776

Looks like Codecov aren't changing tack and we're now getting very low coverage for recent PRs.

For example https://github.com/python-pillow/Pillow/pull/8039 has 24% (of target 52%, which is also too low):

> [2024-05-02T03:52:34.094Z] ['error'] There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 429 - {'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected available in 1708 seconds.', code='throttled')}

https://github.com/python-pillow/Pillow/actions/runs/8918310280/job/24492714641?pr=8039#step:14:216

So let's add a token to the https://github.com/python-pillow org.

@aclark4life Please will you take care of this? I don't have access to the org settings.

1. Sign in at https://app.codecov.io
2. Go to https://app.codecov.io/gh/python-pillow/Pillow/settings
3. Copy the repository upload token
4. Go to https://github.com/organizations/python-pillow/settings/secrets/actions
5. Click "New org secret"
6. Name it `CODECOV_ORG_TOKEN` and paste in the token, leave "Repo access: Public repos" and "Add secret"

After that, we need to add it to our CI workflows and bump to v4, either like:

```yml
- uses: codecov/codecov-action@v4
  with:
    token: ${{ secrets.CODECOV_ORG_TOKEN }}
```

or:

```yml
- uses: codecov/codecov-action@v4
  with:
    ...
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
```

https://github.com/marketplace/actions/codecov shows `env:`, but https://github.com/codecov/feedback/issues/112 also shows the more compact `token:`.
